apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-sql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-sql
  template:
    metadata:
      labels:
        app: my-sql
    spec:
      containers:
        - name: my-sql
          image: mysql:latest
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-pssword
          volumeMounts:
            - name: data-volume
              mountPath: var/lib/mysql
            - name: mysql-config
              mountPath: etc/mysql/conf.d
              readOnly: true
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
  volumeClaimTemplates:
    - metadata:
        name: data-volume
      spec:
        storageClassName: gcp-storage-class
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi

            