apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: example-cronjob
        spec:
          containers:
            - name: example-cronjob
              image: busybox
              command: ["sh", "-c", "echo Hello from cronJob && date"]
          restartPolicy: Never