# go to google cloud console and create a file store manually
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-volume
              mountPath: /pv-vol-data
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: manual-disk-pvc
