apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-database
  template:
    metadata:
      labels:
        app: todo-database
    spec:
      containers:
        - name: todo-database
          image: mongo
          ports:
            - containerPort: 27017
         

---
apiVersion: v1
kind: Service
metadata:
  name: todo-database
spec:
  type: ClusterIP
  selector:
    app: todo-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017