apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: #<deployment name>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
